//go:build ignore

/*
List duplicates in two files:

	grep -xFf enNouns.txt enVerbs.txt

Randomize lines:

	sort -R enVerbs.txt > temp.txt
*/
package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/dkotik/kidwords/internal"
)

var (
	source      = flag.String("source", "", "file to load")
	destination = flag.String("destination", "", "file to save to")
	variable    = flag.String("variable", "", "variable name")
)

func createDictionary(destination, source, variable string) (err error) {
	// words := make([]string, 256)

	f, err := os.Open(source)
	if err != nil {
		return err
	}
	defer f.Close()

	out, err := os.Create(destination)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.WriteString(out, "package kidwords\n\n// Autogenerated file from "+source+"\n\nvar "+variable+" = Dictionary{\n")
	if err != nil {
		return err
	}
	for word, err := range internal.Load(f) {
		if err != nil {
			return err
		}
		if _, err = fmt.Fprintf(out, "\t%q,\n", word); err != nil {
			return err
		}
	}
	_, err = io.WriteString(out, "}\n")
	if err != nil {
		return err
	}
	return nil
}

func main() {
	flag.Parse()
	// _, err := os.Stat(*destination)
	// if err == nil || !errors.Is(err, os.ErrNotExist) {
	// 	fmt.Printf("[INFO] file %s already exists, skipping\n", *destination)
	// 	return
	// }
	if err := createDictionary(*destination, *source, *variable); err != nil {
		panic(err)
	}
}
