//go:build ignore

package main

import (
	"flag"
	"fmt"
	"io"
	"math/rand"
	"os"
	"time"

	"github.com/dkotik/kidwords/dictionary"
)

var (
	source      = flag.String("source", "", "file to load")
	destination = flag.String("destination", "", "file to save to")
	variable    = flag.String("variable", "", "variable name")
)

func createDictionary(destination, source, variable string) (err error) {
	// words := make([]string, 256)

	f, err := os.Open(source)
	if err != nil {
		return err
	}
	defer f.Close()

	dictionary, err := dictionary.Load(f)
	if err != nil {
		return err
	}
	if err = dictionary.Validate(); err != nil {
		return err
	}
	// s := &scanner.Scanner{}
	// s.Init(f)
	// s.Error = func(s *scanner.Scanner, msg string) {
	// 	err = errors.New(msg)
	// }
	//
	// for i := 0; i < 256; i++ {
	// 	s.Scan()
	// 	if err != nil {
	// 		return err
	// 	}
	// 	words[i] = s.TokenText()
	// }

	// b, err := os.ReadFile(source)
	// if err != nil {
	// 	return err
	// }
	// words := bytes.Fields(b)[:256]
	// rand.Shuffle(256, func(i int, j int) {
	// 	words[i], words[j] = words[j], words[i]
	// })

	out, err := os.OpenFile(destination, os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.WriteString(out, "package dictionary\n\n// Autogenerated file from "+source+"\n\nvar "+variable+" = Dictionary{\n")
	if err != nil {
		return err
	}
	for _, word := range dictionary {
		if _, err = fmt.Fprintf(out, "\t%q,\n", word); err != nil {
			return err
		}
	}
	_, err = io.WriteString(out, "}\n")
	if err != nil {
		return err
	}
	return nil
}

func main() {
	flag.Parse()
	// _, err := os.Stat(*destination)
	// if err == nil || !errors.Is(err, os.ErrNotExist) {
	// 	fmt.Printf("[INFO] file %s already exists, skipping\n", *destination)
	// 	return
	// }
	rand.Seed(time.Now().UnixNano())
	if err := createDictionary(*destination, *source, *variable); err != nil {
		panic(err)
	}
}
